we changed the limit change value from .5 to .01
ToasterTech/RobotCode2021 pull request #3
Opened 2021-02-13 23:03 UTC by jerestet37

we changed the limit change value from .5 to .01

2021-02-13 23:07 UTC, tylerallen40 requested changes

2021-02-13 23:07 UTC, tylerallen40 commented on src/main/java/frc/robot/Robot.java
> +    // List<DeviceOutputCommand> shooterCommands = shooterSubsystem.run(model.shooterModel.orElse(new ShooterSubsystemModel(ShooterSubsystemModel.ShooterState.STOPPED)));
Lets uncomment these lines before merging, it is not correct and also causing test failures

2021-02-13 23:07 UTC, tylerallen40 commented on src/main/java/frc/robot/Robot.java
> +            // hangerCommands,
same as above

2021-02-13 23:07 UTC, tylerallen40 commented on src/main/java/frc/robot/controllers/TankDrive.java
> +    this.currentValueLeft = this.limitChange((double)inputMap.get(this.leftJoystickName).getValue(), this.currentValueLeft, 0.01);
This could use some more fine tuning possibly, but it is fine for now

2021-02-20 22:08 UTC, tylerallen40 approved these changes

2021-02-20 22:09 UTC, merged

2021-02-20 22:11 UTC, jerestet37 reviewed
looks good